# Generated by Django 5.0.6 on 2024-07-11 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DaysOfWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("пн", "пн"),
                            ("вт", "вт"),
                            ("ср", "ср"),
                            ("чт", "чт"),
                            ("пт", "пт"),
                            ("сб", "сб"),
                            ("вс", "вс"),
                        ],
                        default="пн",
                        max_length=2,
                        verbose_name="Дни недели",
                    ),
                ),
            ],
            options={
                "verbose_name": "день",
                "verbose_name_plural": "дни",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="место, в котором необходимо выполнять привычку",
                        max_length=150,
                        verbose_name="Место",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="действие, которое представляет собой привычка,Отвечает на вопрос: 'Что делать?'.",
                        max_length=150,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Каждый день", "Каждый день"),
                            ("Выбрать дни недели", "Выбрать дни недели"),
                        ],
                        default="Каждый день",
                        max_length=30,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="время, когда необходимо выполнять привычку",
                        verbose_name="Время начала действия",
                    ),
                ),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        blank=True,
                        help_text="чем пользователь должен себя вознаградить после выполнения",
                        max_length=150,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="время на выполнение привычки (в секундах)",
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Время выполнения действия",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Статус публичности"
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="указывать только для полезных привычек",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="useful_habit",
                        to="habits.habit",
                        verbose_name="связанная привычка",
                    ),
                ),
                (
                    "days",
                    models.ManyToManyField(
                        help_text="Выбери дни недели",
                        related_name="habit",
                        to="habits.daysofweek",
                        verbose_name="Выбор дней недели",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habit",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
                "ordering": ["-pk"],
            },
        ),
    ]
